apiVersion: v1
kind: Service
metadata:
  name: gear-service
  labels:
    app: gear-service
spec:
  ports:
    - port: 8080
  selector:
    app: gear-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gear-service
  labels:
    app: gear-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gear-service
  template:
    metadata:
      labels:
        app: gear-service
    spec:
      containers:
        - image: lwluc/gear-service
          name: gear-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          # resources:
          #   limits:
          #     memory: "1Gi"
          #     cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 7
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            failureThreshold: 5
            periodSeconds: 5
      restartPolicy: Always
